# Generated by Django 3.0.3 on 2020-04-19 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='request_delivery_date',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_delivery_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='order',
            name='supplier_delivery_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
