# Generated by Django 3.0.3 on 2020-04-19 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0002_auto_20200419_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_delivery_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='order',
            name='supplier_delivery_date',
        ),
        migrations.AddField(
            model_name='ordernumber',
            name='customer_delivery_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='ordernumber',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ordernumber',
            name='supplier_delivery_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
