# Generated by Django 3.0.3 on 2020-04-21 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0002_auto_20200421_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='employee_number',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that employee_number  already exists.'}, max_length=5, unique=True, verbose_name='employee_number'),
        ),
    ]
