# Generated by Django 3.0.3 on 2020-04-21 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0003_auto_20200421_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernumber',
            name='user',
            field=models.ForeignKey(default=57954, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
