# Generated by Django 3.0.3 on 2020-04-22 01:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0004_ordernumber_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordernumber',
            name='customer_delivery_date',
        ),
        migrations.RemoveField(
            model_name='ordernumber',
            name='supplier_delivery_date',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_delivery_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='order',
            name='supplier_delivery_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='ordernumber',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
