# Generated by Django 3.0.3 on 2020-04-22 01:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0005_auto_20200422_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordernumber',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
