# Generated by Django 3.0.3 on 2020-04-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0006_auto_20200427_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
