# Generated by Django 3.0.3 on 2020-04-28 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0007_order_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptance',
            name='order_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omsapp.Order'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='order_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omsapp.Order'),
        ),
    ]
