# Generated by Django 3.0.3 on 2020-05-03 15:37

from django.db import migrations, models
import omsapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0009_auto_20200502_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='customer_code',
        ),
        migrations.AlterField(
            model_name='item',
            name='item_code',
            field=models.IntegerField(default=omsapp.models.get_next, unique=True),
        ),
    ]
