# Generated by Django 3.0.3 on 2020-05-03 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0010_auto_20200503_1537'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
