# Generated by Django 3.0.3 on 2020-05-03 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0012_currency_b_currency_s'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='buy_price_cur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='omsapp.Currency_B'),
        ),
        migrations.AddField(
            model_name='item',
            name='sell_price_cur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='omsapp.Currency_S'),
        ),
    ]
