# Generated by Django 3.0.3 on 2020-05-03 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0013_auto_20200503_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='customer',
        ),
        migrations.AddField(
            model_name='project',
            name='customer_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='omsapp.Customer'),
        ),
    ]
