# Generated by Django 3.0.3 on 2020-05-03 16:37

from django.db import migrations, models
import omsapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0014_auto_20200503_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_code',
            field=models.CharField(default=omsapp.models.get_next, max_length=5, unique=True),
        ),
    ]
