# Generated by Django 3.0.3 on 2020-05-03 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0015_auto_20200503_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='customer_code',
            new_name='customer',
        ),
    ]
