# Generated by Django 3.0.5 on 2020-05-07 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0016_auto_20200503_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
